openai:
  api_key: "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"  # Replace with your actual OpenAI API key